name: traj-pred
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - torchvision=0.12.0=py38_cu113
  - torchaudio=0.11.0=py38_cu113
  - cudatoolkit=11.3
  - matplotlib=3.5.1
  - numpy=1.21.5
  - pandas=1.4.2
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - pillow=9.0.1
  - pip
  - pip:
    - tensorboard==2.8.0
    - torch-scatter==2.0.9
    - torch-sparse==0.6.13
    - torchmetrics==0.8.0
    - tqdm==4.64.0
    - pyyaml==6.0
    - joblib==1.1.0
    - jinja2==3.1.1
    - cachetools==5.0.0
    - typing-extensions==4.1.1
    - protobuf==3.20.0
    - absl-py==1.0.0
    - fsspec==2022.3.0
    - requests==2.27.1
